# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mqtt-cloud-pubsub-connector
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-cloud-pubsub-connector
spec:
  selector:
    matchLabels:
      app: mqtt-cloud-pubsub-connector
  template:
    metadata:
      labels:
        app: mqtt-cloud-pubsub-connector
    spec:
      containers:
        # We set a more precise container image ID with Kustomize
        - image: mqtt-cloud-pubsub-connector
          name: mqtt-cloud-pubsub-connector
          resources:
            # Setting limits same as requests because GKE Autopilot only considers requests
            # See https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#resource-limits
            limits:
              cpu: "1000m"
              ephemeral-storage: "1Gi"
              memory: "1Gi"
            requests:
              cpu: "1000m"
              ephemeral-storage: "1Gi"
              memory: "1Gi"
          volumeMounts:
            - name: mqtt-cloud-pubsub-connector-config
              mountPath: "/usr/src/app/config"
              readOnly: true
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountName: mqtt-cloud-pubsub-connector
      volumes:
        - name: mqtt-cloud-pubsub-connector-config
          configMap:
            name: mqtt-cloud-pubsub-connector
            items:
              - key: "application.properties"
                path: "application.properties"
              - key: "application-prod.properties"
                path: "application-prod.properties"
...
