---
# Options reference: https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Establish a baseline so we don't have to fix these issues at the same time
# as we ship Checkov with super-linter.
baseline: config/lint/.checkov.baseline

# Report skipped baseline checks in the output
output-baseline-as-skipped: true

# Don't report passed checks in output
quiet: true
...
