---
name: Dependabot automation

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve the PR
        run: gh pr review --approve "${PR_URL}"
      - name: Enable auto-merge for patch updates PR
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
          || steps.metadata.outputs.dependency-names == 'actions/checkout'
          || steps.metadata.outputs.dependency-names == 'com.diffplug.spotless'
          || steps.metadata.outputs.dependency-names == 'docker/build-push-action'
          || steps.metadata.outputs.dependency-names == 'docker/metadata-action'
          || steps.metadata.outputs.dependency-names == 'docker/setup-buildx-action'
          || steps.metadata.outputs.dependency-names == 'docker/setup-qemu-action'
          || steps.metadata.outputs.dependency-names == 'google.com/cloudsdktool/google-cloud-cli'
          || steps.metadata.outputs.dependency-names == 'hashicorp/google-beta'
          || steps.metadata.outputs.dependency-names == 'hashicorp/google'
          || steps.metadata.outputs.dependency-names == 'hashicorp/setup-terraform'
          || steps.metadata.outputs.dependency-names == 'hashicorp/terraform'
          || steps.metadata.outputs.dependency-names == 'numpy'
          || steps.metadata.outputs.dependency-names == 'org.assertj:assertj-core'
          || steps.metadata.outputs.dependency-names == 'super-linter/super-linter'
          || steps.metadata.outputs.dependency-names == 'terraform-google-modules/cloud-router/google'
          || steps.metadata.outputs.dependency-names == 'terraform-google-modules/cloud-storage/google'
          || steps.metadata.outputs.dependency-names == 'terraform-google-modules/kubernetes-engine/google'
          || steps.metadata.outputs.dependency-names == 'terraform-google-modules/network/google'
          || steps.metadata.outputs.dependency-names == 'terraform-google-modules/project-factory/google'
          || steps.metadata.outputs.dependency-names == 'vscode/devcontainers/java'
        run: gh pr merge --auto --squash --delete-branch "${PR_URL}"
...
